# Generated by Django 3.1.4 on 2021-01-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='name',
        ),
        migrations.AddField(
            model_name='productimage',
            name='name',
            field=models.ManyToManyField(default=None, to='core.Product'),
        ),
    ]
