# Generated by Django 3.1.5 on 2021-01-07 18:33

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210107_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=0, editable=False, populate_from='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=35),
        ),
    ]
