# Generated by Django 3.1.5 on 2021-01-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210107_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(0, 'Seçilməyib'), (1, 'Yoxlama prosesində'), (2, 'Qəbul edilib'), (3, 'Qəbul edilməyib')], default=0),
        ),
    ]
