# Generated by Django 3.1.5 on 2021-01-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210108_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='Yeni?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery',
            field=models.BooleanField(default=False, verbose_name='Çatdırılma'),
        ),
    ]
