# Generated by Django 3.1.5 on 2021-01-13 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210109_1800'),
        ('core', '0006_auto_20210108_0130'),
    ]

    operations = [
    ]
